### ISSUE TITLE
Search Mediaitems

### ISSUE THREAD

**Issue by sebingel** [bennygr/noised#6]
As a user i want to search Mediaitems in all available sources or in a defined set of available sources.

**Comment by sebingel** [comment]
Isn't this issue already resolved by Noised.Plugins.Commands.CoreCommands.Search?

**Comment by bennygr** [comment]
Basically, yes. But we are still missing functionality for getting a list of available sources and the option to query  one or more specific source(s) rather than searching in all sources.
